// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpxFNd9hy9Bzmr6inRK6RcmIA_7kZuo-Y',
    appId: '1:613702979739:web:74fc7bde893b1fb538f63e',
    messagingSenderId: '613702979739',
    projectId: 'agile-falcon-401605',
    authDomain: 'agile-falcon-401605.firebaseapp.com',
    databaseURL: 'https://agile-falcon-401605-default-rtdb.firebaseio.com',
    storageBucket: 'agile-falcon-401605.appspot.com',
    measurementId: 'G-9020KMTRKV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDExqyHcP6wx7jxEmbDJ4VtQ4NoEvdvdSw',
    appId: '1:613702979739:android:0b133014f3b03caf38f63e',
    messagingSenderId: '613702979739',
    projectId: 'agile-falcon-401605',
    databaseURL: 'https://agile-falcon-401605-default-rtdb.firebaseio.com',
    storageBucket: 'agile-falcon-401605.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAUJUtjhZnf1TulfPn3SUZc3WxYJy8Jtg',
    appId: '1:613702979739:ios:58e3120b01101c0d38f63e',
    messagingSenderId: '613702979739',
    projectId: 'agile-falcon-401605',
    databaseURL: 'https://agile-falcon-401605-default-rtdb.firebaseio.com',
    storageBucket: 'agile-falcon-401605.appspot.com',
    iosBundleId: 'com.example.timeSheetFlutterApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAAUJUtjhZnf1TulfPn3SUZc3WxYJy8Jtg',
    appId: '1:613702979739:ios:9ff3cc5f59d1872d38f63e',
    messagingSenderId: '613702979739',
    projectId: 'agile-falcon-401605',
    databaseURL: 'https://agile-falcon-401605-default-rtdb.firebaseio.com',
    storageBucket: 'agile-falcon-401605.appspot.com',
    iosBundleId: 'com.example.timeSheetFlutterApplication.RunnerTests',
  );
}
